/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;
import java.sql.Date; 
import java.text.SimpleDateFormat;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import java.time.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Calendar;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class Pointage extends javax.swing.JFrame {

    /**
     * Creates new form Pointage
     */
    public Pointage() {
        initComponents();
        liste();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Epm = new javax.swing.JTextField();
        txt_pointage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Ajouter2 = new javax.swing.JButton();
        btn_Supprimer2 = new javax.swing.JButton();
        btn_afficher2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Pointage = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_recherche2 = new javax.swing.JTextField();
        btn_Modifier2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datepoin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(41, 22, 74));
        jPanel2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Listes des Pointages");

        txt_Epm.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txt_Epm.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_pointage.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txt_pointage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date Pointage");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("N° Employe");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pointage");

        btn_Ajouter2.setBackground(new java.awt.Color(0, 153, 204));
        btn_Ajouter2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btn_Ajouter2.setText("Ajouter");
        btn_Ajouter2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Ajouter2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Ajouter2MouseClicked(evt);
            }
        });
        btn_Ajouter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ajouter2ActionPerformed(evt);
            }
        });

        btn_Supprimer2.setBackground(new java.awt.Color(255, 0, 0));
        btn_Supprimer2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btn_Supprimer2.setText("Supprimer");
        btn_Supprimer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Supprimer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Supprimer2MouseClicked(evt);
            }
        });
        btn_Supprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Supprimer2ActionPerformed(evt);
            }
        });

        btn_afficher2.setBackground(new java.awt.Color(204, 204, 255));
        btn_afficher2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btn_afficher2.setText("Récuperer");
        btn_afficher2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_afficher2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_afficher2MouseClicked(evt);
            }
        });
        btn_afficher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_afficher2ActionPerformed(evt);
            }
        });

        table_Pointage.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        table_Pointage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date Pointage", "N° Employe", "Pointage"
            }
        ));
        table_Pointage.setEditingRow(5);
        table_Pointage.setRowHeight(25);
        table_Pointage.setRowMargin(3);
        jScrollPane2.setViewportView(table_Pointage);

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recherche");

        txt_recherche2.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txt_recherche2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_recherche2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_recherche2MouseClicked(evt);
            }
        });
        txt_recherche2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_recherche2ActionPerformed(evt);
            }
        });

        btn_Modifier2.setBackground(new java.awt.Color(0, 204, 0));
        btn_Modifier2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btn_Modifier2.setText("Modifier");
        btn_Modifier2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Modifier2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Modifier2MouseClicked(evt);
            }
        });
        btn_Modifier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modifier2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Gestion de pointage et Congé de personnel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        datepoin.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        datepoin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datepoin, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(txt_Epm, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(btn_Ajouter2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Supprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Modifier2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_pointage, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_afficher2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_recherche2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datepoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pointage, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(txt_Epm))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ajouter2)
                    .addComponent(btn_Supprimer2)
                    .addComponent(btn_Modifier2)
                    .addComponent(btn_afficher2))
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_recherche2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void liste(){
               try {
                    table_Pointage.setDefaultEditor(Object.class, null);
            Connection connexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_pointage", "root", "");
            String sql = "SELECT * FROM pointage";
            PreparedStatement statement = connexion.prepareStatement(sql);
            ResultSet result = statement.executeQuery();

            DefaultTableModel model = (DefaultTableModel) table_Pointage.getModel();
            model.setRowCount(0);
            while (result.next()) {
                Object[] row = {
                    result.getDate("datePointage"),
                    result.getString("NumEmp"),
                    result.getString("pointage"),
                   
                };
                model.addRow(row);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur lors du chargement des données : " + ex.getMessage());
        }
        }
        
        private void modifierPointage(Date datPoint, String NumEmp, String point) {
            
            
    try {
        Connection connexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_pointage", "root", "");
        String sql = "UPDATE pointage SET datePointage = ?, pointage = ? WHERE NumEmp = ?";
        PreparedStatement statement = connexion.prepareStatement(sql);
        statement.setDate(1, new java.sql.Date(datPoint.getTime())); 
        statement.setString(2, point);
        statement.setString(3, NumEmp);

        int rowsUpdated = statement.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Pointage modifié avec succès !");

            
            txt_Epm.setText("");
            txt_pointage.setText("");
            datepoin.setText("");

         
            liste();
        } else {
            JOptionPane.showMessageDialog(this, "Aucune modification effectuée !");
        }

        connexion.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erreur lors de la modification du pointage : " + ex.getMessage());
    }
}


    
    
    
    private void btn_Ajouter2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ajouter2MouseClicked
        if ( txt_Epm.getText().isEmpty() || txt_pointage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vous avez remplir !");
        } else {
            try {

                Connection connexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_pointage", "root", "");
                String sql = "INSERT INTO pointage (datePointage, NumEmp, pointage) VALUES (?, ?, ?)";
                PreparedStatement statement = connexion.prepareStatement(sql);
              statement.setString(1, datepoin.getText());
                statement.setString(2, txt_Epm.getText());
                statement.setString(3, txt_pointage.getText());
                int row = statement.executeUpdate();

                if (row > 0) {
                    JOptionPane.showMessageDialog(this, "Pointage ajouté avec succès !");
                   
                    datepoin.setText("");
                    txt_Epm.setText("");
                    txt_pointage.setText("");
                    liste();
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Échec de l'ajout de la pointage !");
                }
                connexion.close();

            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Numéro employe n'est pas existe");
            }
        }
    }//GEN-LAST:event_btn_Ajouter2MouseClicked

    private void btn_Ajouter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ajouter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Ajouter2ActionPerformed

    private void btn_Supprimer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Supprimer2MouseClicked
        
    }//GEN-LAST:event_btn_Supprimer2MouseClicked

    private void btn_Supprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Supprimer2ActionPerformed
        int selectedRow = table_Pointage.getSelectedRow();
        if (selectedRow != -1) {
            String numEmp = (String) table_Pointage.getValueAt(selectedRow, 1);
            try {
                Connection connexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_pointage", "root", "");
                String sql = "DELETE FROM pointage WHERE NumEmp = ?";
                PreparedStatement statement = connexion.prepareStatement(sql);
                statement.setString(1, numEmp);
                int rowsDeleted = statement.executeUpdate();
                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "pointage supprimé avec succès !");
                    liste();
                   
                    //chargerDonneesTable();

                }
                connexion.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erreur lors de la suppression de la pointage : " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un pointage à supprimer.");
        }
    }//GEN-LAST:event_btn_Supprimer2ActionPerformed

    private void btn_afficher2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_afficher2MouseClicked
                   int selectedRow = table_Pointage.getSelectedRow();
        if (selectedRow != -1) {
        java.util.Date datePoint = (java.util.Date) table_Pointage.getValueAt(selectedRow, 0);
        String NumEmp = (String) table_Pointage.getValueAt(selectedRow, 1);
        String pointage = (String) table_Pointage.getValueAt(selectedRow, 2);
       
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
         String dateDebutStr = dateFormat.format(datepoin);
        txt_Epm.setText(NumEmp);
        txt_pointage.setText(pointage);

    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un employé à modifier.");
        return;
    }
    }//GEN-LAST:event_btn_afficher2MouseClicked

    private void btn_afficher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_afficher2ActionPerformed
      liste();
    }//GEN-LAST:event_btn_afficher2ActionPerformed

    private void txt_recherche2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_recherche2MouseClicked

    }//GEN-LAST:event_txt_recherche2MouseClicked

    private void txt_recherche2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_recherche2ActionPerformed
        String recherche = txt_recherche2.getText();
        if (!recherche.isEmpty()) {
            try {
                Connection connexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_pointage", "root", "");
                String sql = "SELECT * FROM pointage WHERE DatePointage LIKE ?";
                PreparedStatement statement = connexion.prepareStatement(sql);
                statement.setString(1, "%" + recherche + "%");
                statement.setString(2, "%" + recherche + "%");
                ResultSet result = statement.executeQuery();
                DefaultTableModel model = (DefaultTableModel) table_Pointage.getModel();
                model.setRowCount(0);
                liste();
                while (result.next()) {
                    Object[] row = {
                        result.getString("NumEmp"),
                        result.getString("Nom"),
                        result.getString("Prenom"),
                        result.getString("poste"),
                        result.getInt("Salaire")
                          
                    };
                    model.addRow(row);
                }

                connexion.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erreur lors de la recherche : " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez saisir un terme de recherche.");
        }// TODO add your handling code here:
    }//GEN-LAST:event_txt_recherche2ActionPerformed

    private void btn_Modifier2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Modifier2MouseClicked
        String datPoint = datepoin.getText();
        String NumEmp = txt_Epm.getText();
        String point = txt_pointage.getText();
       
 
         modifierpointage( datPoint,  NumEmp, point);
    }//GEN-LAST:event_btn_Modifier2MouseClicked

    private void btn_Modifier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modifier2ActionPerformed
       

       

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Modifier2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pointage().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ajouter2;
    private javax.swing.JButton btn_Modifier2;
    private javax.swing.JButton btn_Supprimer2;
    private javax.swing.JButton btn_afficher2;
    private javax.swing.JTextField datepoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_Pointage;
    private javax.swing.JTextField txt_Epm;
    private javax.swing.JTextField txt_pointage;
    private javax.swing.JTextField txt_recherche2;
    // End of variables declaration//GEN-END:variables

    private void modifierpointage(String datPoint, String NumEmp, String point) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
